import Head from 'next/head';
import Visitor from '../layouts/visitor/visitor';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>
    </div>
  );
}

Home.getLayout = (page) => <Visitor>{page}</Visitor>;
