import Head from 'next/head';
import Image from 'next/image';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function getStaticProps() {
  const products = await prisma.product.findMany();

  return {
    props: { products },
  };
}

export default function Home({ products }) {
  console.log(products);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>
    </div>
  );
}
